# Generated by Django 4.2.13 on 2024-06-19 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0002_alter_qc_qc_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencing',
            name='qc',
        ),
        migrations.AddField(
            model_name='sequencing',
            name='extraction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lims_core.extraction'),
            preserve_default=False,
        ),
    ]
