# Generated by Django 4.2.13 on 2024-06-19 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0003_remove_sequencing_qc_sequencing_extraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='extraction_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 7, 47, 321040), verbose_name='date extracted'),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='extraction_method',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='isPass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qc',
            name='qc_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 7, 47, 321219), verbose_name='date qc'),
        ),
        migrations.AlterField(
            model_name='qc',
            name='qc_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sequencing',
            name='sequencing_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 7, 47, 321377), verbose_name='date sequenced'),
        ),
        migrations.AlterField(
            model_name='sequencing',
            name='sequencing_method',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sequencing',
            name='sequencing_read_length',
            field=models.IntegerField(default=0),
        ),
    ]
